### ISSUE TITLE
Can I save and load a ReactionNetwork?

### ISSUE THREAD

**Issue by Imhaenoo** [materialsproject/reaction-network#268]
Hello, a thankful developer.

I'm using reaction networks to explore synthetic pathways for various materials.
And I want to build various reaction networks by changing the entries, which can be adjust based on temperature or stability.

Even if there are only 100 entries, building a reactive network will take 1-2 hours (with about 1 million reactions).
Refer to the image (CPU is 32 cores)
 
![image](https://github.com/materialsproject/reaction-network/assets/97152267/fa3ed532-a3a7-45e9-8438-05f7a198a02b)

So, I want to save the react network once it's built and load it when I need it.

Is there any way to save and load a reactive network?

Thank you !

**Comment by mattmcdermott** [comment]
Hi @Imhaenoo,

Can you try using monty's `dumpfn` and `loadfn`? Since switching to graphs in rustworkx, we should be able to save in a JSON-serialized form.

```
from monty.serialization import dumpfn, loadfn

dumpfn(MY_REACTION_NETWORK, "rn.json.gz")
test_load_rn = loadfn("rn.json.gz")
```
Let me know if this doesn't work and I will see if I can fix

**Comment by Imhaenoo** [comment]
It works very well!

Thank you very much for your quick reply.

**Comment by mattmcdermott** [comment]
Great!!
