### ISSUE TITLE
[BUG] GibbsComputedEntry.from_structure creates unexpected input for phase diagrams when input structure contains Species in its composition

### ISSUE THREAD

**Issue by amalie-trewartha** [materialsproject/reaction-network#275]
When from_structure is called using a structure object with Species in its composition as input, the resulting GibbsComputedEnergy object will have a composition with Species objects. This will then cause creation of phase diagrams using that entry to fail to identify the correct chemsys.
This could be fixed by changing line 273 in gibbs.py to;
        composition = Composition(structure.composition).element_composition

**Comment by mattmcdermott** [comment]
@amalie-trewartha Thanks for the catch, Amalie! I was able to recreate the bug and fix it with your suggestion.

**Comment by mattmcdermott** [comment]
Closed with #276
